### PR TITLE
Make examples actual examples

### PR DESCRIPTION
**Pull request by Speykious**
With this PR, all examples in the example folder are actual examples from the point of view of Cargo.
This means we can now just execute commands like `cargo run --example calculator` from the root of the project.

This probably breaks Android compilation though, as the `[lib]` section is no longer there due to all the example-specific `Cargo.toml` files being gone. Additional tests are needed on Android to find a proper solution.

### CODE REVIEW

**Comment by limikael** [comment]
As a source of inspiration perhaps... I saw that cargo-apk has examples as well:

https://github.com/rust-mobile/cargo-apk/blob/main/examples/Cargo.toml

They use `crate-type = ["cdylib"]` I see... Is there anything else "non-standard" they do?

**Comment by Speykious** [comment]
Oh, that's interesting, I didn't know you could specify a crate type for an example! It seems like that's exactly what we want to do here, except only when compiling for Android.

Edit: considering the nature of their project, that's the most standard thing they could've done. The examples are actually registered as examples.

**Comment by Speykious** [comment]
I found something interesting in [cargo-quad-apk](https://github.com/not-fl3/cargo-quad-apk): they have an `example` field in their augmented Cargo.toml config specifically for Android.
https://github.com/not-fl3/cargo-quad-apk/blob/master/src/config.rs#L460

Maybe you could do something similar with a cargo-apk or cargo-quad-apk fork?

**Comment by limikael** [comment]
What is "augmented Cargo.toml"? Is it a Cargo.toml they sort of build on the fly?

Would prefer not to have to fork cargo-apk ... 

Anyway... If it would somehow be possible to have one specific example that is set up for android, but the other ones only work for desktop, then it would also be ok, I think... Would it be doable that way?

Edit: To elaborate...

The normal examples could be in the examples dir, like a standard rust project... And then we can have an android-example dir with a separate project that work on Android... Perhaps, the standard examples would then also be runnable with cargo-quad-apk if we are lucky... What do you think about this?

**Comment by limikael** [comment]
I added `--example` functionality to [cargo-sdl-apk](https://crates.io/crates/cargo-sdl-apk). So now the examples have been made into real examples. It doesn't work with Glutin and cargo-apk, so SDL is now considered the default.

**Pull request closed without merging**
