### PR TITLE
Tidying Up: Fix clippy warnings and run cargo fmt

### PR DESCRIPTION
**Pull request by rtkay123**

### CODE REVIEW

**Comment by Speykious** [comment]
Lol I was doing it myself. xD

You forgot to run cargo fmt on `apply-macros` and the examples, and to format the `.toml` files too

**Comment by rtkay123** [comment]
How would you prefer to go about the `.toml` formatting?

I can sort out the clippy and fmt on `appy-macros` quickly. Though i'm not sure how to go about `.toml` formatting. Is there a style guide to follow?

**Comment by Speykious** [comment]
> How would you prefer to go about the `.toml` formatting?
> 
> I can sort out the clippy and fmt on `appy-macros` quickly. Though i'm not sure how to go about `.toml` formatting. Is there a style guide to follow?

Spaces between curly braces and equals, mostly. Though the easiest is just to format with VSCode using CTRL+SHIFT+I.
If you don't use VSCode I don't know how to do it, but I assume there must be a CLI tool for it which relies on that standard

**Comment by rtkay123** [comment]
Yeah I don't use vscode. Let me see what I can do :)

**Comment by Speykious** [comment]
What do you use, Neovim?

**Comment by rtkay123** [comment]
Correct, I use Neovim. Prettier has a toml plugin so I could use that?

**Comment by limikael** [comment]
Thanks a lot!!!

**Pull request merged**
